# Romance channel configuration  
name: "로맨스 이야기"
youtube_channel_id: "YOUR_ROMANCE_CHANNEL_ID"
tags:
  - "로맨스"
  - "사랑이야기"
  - "감동"
  - "shorts"
  - "연애"

prompt_template: |
  감동적인 사랑 이야기를 만들어주세요.
  
  조건:
  - 270-300자 내외
  - 현실적이면서도 로맨틱한 내용
  - 감동적인 순간 포함
  - 희망적인 메시지
  
  형식:
  제목: [이야기 제목]
  내용: [이야기 내용]

scene_style: "romantic atmosphere, soft lighting, pastel colors, Korean drama style, emotional"