# Production Profile
# Optimized settings for production/CI environment

# Conservative settings for production
build:
  timeout: 3600 # Standard timeout
  parallel_jobs: 4 # Conservative parallel jobs
  allow_unfree: false # Strict licensing
  experimental_features: 'nix-command flakes'

development:
  debug_mode: false
  verbose_logging: false
  test_mode: false
  performance_monitoring: false

# Production security settings
security:
  strict_permissions: true
  verify_signatures: true
  sandbox_mode: true
  allow_insecure_protocols: false

# Minimal resource usage
resource_management:
  memory_conservative: true
  disk_cleanup: true
  network_efficient: true
