# YAML Lint configuration for dotfiles project
# Balances strictness with practical flexibility

extends: default

rules:
  # Line length - accommodate longer configuration values
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation - standard 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true

  # Comments - allow flexible comment positioning
  comments:
    min-spaces-from-content: 1

  # Document formatting
  document-start: disable  # Allow files without ---
  document-end: disable    # Allow files without ...

  # Truthy values - allow yes/no, on/off for Nix compatibility
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  # Brackets and braces - allow some flexibility
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  # Empty lines
  empty-lines:
    max: 2
    max-start: 1
    max-end: 1

ignore: |
  *.secrets.yaml
  **/secrets/**
  .github/workflows/
