# Test configuration for Docker Compose
# This file is used to validate the Docker Compose setup
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - APP_ENV=development
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app

volumes:
  redis-data: