# 테스트 시스템

test-all:
	@./tests/run-tests.sh all

test-core:
	@./tests/run-tests.sh core

test-integration:
	@./tests/run-tests.sh integration

test-parallel:
	@./tests/run-tests.sh --parallel all

test-verbose:
	@./tests/run-tests.sh --verbose all

.PHONY: test-all test-core test-integration test-parallel test-verbose
