# Advanced Configuration Settings
# Extended configuration for power users and custom environments

# Development environment settings
development:
  debug_mode: false
  verbose_logging: false
  test_mode: false
  performance_monitoring: true

# Build optimization settings
build_optimization:
  enable_ccache: true
  parallel_builds: true
  memory_limit: "8G"
  disk_cache_size: "10G"
  network_timeout: 300

# Security settings
security:
  strict_permissions: true
  verify_signatures: true
  sandbox_mode: true
  allow_insecure_protocols: false

# Network configuration
network:
  proxy_enabled: false
  proxy_host: ""
  proxy_port: 8080
  dns_servers: ["1.1.1.1", "8.8.8.8"]
  connection_timeout: 30

# Experimental features
experimental:
  new_parser: false
  enhanced_caching: true
  parallel_downloads: true
  smart_rebuilds: true

# User customization
user_preferences:
  color_output: true
  progress_bars: true
  notification_sound: false
  auto_cleanup: true

# Platform-specific advanced settings
platform_advanced:
  darwin:
    use_xcode_tools: true
    homebrew_integration: true
    sandboxing: true
  linux:
    systemd_integration: true
    apparmor_profiles: true
    container_support: true
