# Build configuration settings
# Externalized configuration for build system
build:
  experimental_features:
    - nix-command
    - flakes
  timeout: 3600 # Build timeout in seconds
  parallel_jobs: 4 # Number of parallel build jobs
  darwin:
    allow_unfree: true
    impure_mode: true
  linux:
    allow_unfree: false
    impure_mode: false
# Platform-specific settings
platforms:
  darwin:
    rebuild_command: 'darwin-rebuild'
    config_path: 'darwinConfigurations'
  linux:
    rebuild_command: 'nixos-rebuild'
    config_path: 'nixosConfigurations'
# Architecture mappings
architectures:
  supported:
    - aarch64-darwin
    - x86_64-darwin
    - aarch64-linux
    - x86_64-linux
  aliases:
    arm64: aarch64
    x64: x86_64
