# Directory structure mappings
# Defines the new optimized directory structure

directory_structure:
  apps:
    common: "apps/common"          # Shared logic across platforms
    platforms: "apps/platforms"   # Platform-specific implementations
    targets: "apps/targets"       # Target-specific configurations

  scripts:
    lib: "scripts/lib"            # Common library functions
    platform: "scripts/platform" # Platform-specific overrides
    build: "scripts/build"        # Build-related scripts
    utils: "scripts/utils"        # Utility scripts

  modules:
    shared: "modules/shared"      # Shared Nix modules
    platform: "modules/platform" # Platform-specific modules

  config:
    root: "config"                # External configuration files

# Migration mappings (old -> new)
migration:
  apps:
    "apps/aarch64-darwin": "apps/targets/aarch64-darwin.sh"
    "apps/aarch64-linux": "apps/targets/aarch64-linux.sh"
    "apps/x86_64-darwin": "apps/targets/x86_64-darwin.sh"
    "apps/x86_64-linux": "apps/targets/x86_64-linux.sh"

  modules:
    "modules/darwin": "modules/platform/darwin"
    "modules/nixos": "modules/platform/nixos"
