# Network Configuration
# Settings for network timeouts, connections, and URLs

network:
  # HTTP connection settings
  http:
    connections: 50
    connect_timeout: 5
    download_attempts: 3

  # Repository URLs
  repositories:
    nixpkgs: "github:nixos/nixpkgs/nixos-unstable"
    home_manager: "github:nix-community/home-manager"
    nix_darwin: "github:LnL7/nix-darwin/master"

  # Substituters and trusted keys
  substituters:
    - url: "https://cache.nixos.org"
      public_key: "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY="
    - url: "https://nix-community.cachix.org"
      public_key: "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="

  # Network timeouts
  timeouts:
    build: 3600  # 1 hour
    download: 300  # 5 minutes
    connection: 30  # 30 seconds
