# Performance Configuration
# Settings for build optimization and system performance

performance:
  # Build settings
  build:
    max_jobs: 'auto'
    cores: 0 # Use all available cores
    parallel_builds: true

  # Memory management
  memory:
    min_free: 1073741824 # 1GB in bytes
    max_free: 10737418240 # 10GB in bytes

  # System limits
  system:
    file_descriptors: 4096
    max_user_processes: 2048

  # Nix-specific performance
  nix:
    # Build sandbox settings
    sandbox: true
    build_users_group: 'nixbld'

    # Store optimization
    auto_optimise_store: true

    # Parallel processing
    max_substitution_jobs: 16

  # Cache performance
  cache:
    # Narinfo cache settings (in seconds)
    narinfo_cache_positive_ttl: 3600 # 1 hour
    narinfo_cache_negative_ttl: 60 # 1 minute
