#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM=$(uname -m)

case "$SYSTEM" in
  x86_64)
    FLAKE_TARGET="x86_64-linux"
    ;;
  aarch64)
    FLAKE_TARGET="aarch64-linux"
    ;;
  *)
    echo -e "${RED}Unsupported architecture: $SYSTEM${NC}"
    exit 1
    ;;
esac

export NIXPKGS_ALLOW_UNFREE=1

echo -e "${YELLOW}Starting build...${NC}"
nix --extra-experimental-features 'nix-command flakes' build .#nixosConfigurations.${FLAKE_TARGET}.config.system.build.toplevel "$@"

echo -e "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo -e "${GREEN}Build complete!${NC}"
