# Development environment configuration
app:
  name: "YouTube Shorts Generator"
  env: "dev"
  debug: true

database:
  host: "${DB_HOST}"
  port: 5432
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  dbname: "youtube_shorts_dev"
  sslmode: "require"

api:
  use_mock: false
  
  openai:
    api_key: "${OPENAI_API_KEY}"
    model: "gpt-4"
    max_tokens: 500
    temperature: 0.7
  
  image:
    provider: "stable-diffusion"
    api_key: "${IMAGE_API_KEY}"
    base_url: "https://stablediffusionapi.com/api/v3"
    
  tts:
    provider: "google"
    credentials_file: "${GOOGLE_CREDENTIALS_FILE}"
    language_code: "ko-KR"
    voice_name: "ko-KR-Wavenet-D"

youtube:
  client_id: "${YOUTUBE_CLIENT_ID}"
  client_secret: "${YOUTUBE_CLIENT_SECRET}"
  redirect_url: "${YOUTUBE_REDIRECT_URL}"

storage:
  base_path: "/data/youtube-shorts/dev"
  temp_path: "/data/youtube-shorts/dev/temp"

logging:
  level: "info"
  format: "json"
  output: "file"
  file_path: "/var/log/youtube-shorts/dev.log"