#!/bin/bash -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM=$(uname -m)

case "$SYSTEM" in
x86_64)
  FLAKE_TARGET="x86_64-linux"
  ;;
aarch64)
  FLAKE_TARGET="aarch64-linux"
  ;;
*)
  printf "%b%s%b\n" "$RED" "Unsupported architecture: $SYSTEM" "$NC"
  exit 1
  ;;
esac

export NIXPKGS_ALLOW_UNFREE=1

printf "%b%s%b\n" "$YELLOW" "Starting build..." "$NC"
nix --extra-experimental-features 'nix-command flakes' build .#nixosConfigurations.${FLAKE_TARGET}.config.system.build.toplevel "$@"

printf "%b%s%b\n" "$YELLOW" "Cleaning up..." "$NC"
unlink ./result

printf "%b%s%b\n" "$GREEN" "Build complete!" "$NC"
