#!/bin/bash -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

SYSTEM_TYPE="x86_64-darwin"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

export NIXPKGS_ALLOW_UNFREE=1

# Set USER if not already set
if [ -z "$USER" ]; then
    USER=$(whoami)
    export USER
fi

printf "%b%s%b\n" "$YELLOW" "Starting build..." "$NC"
nix --extra-experimental-features 'nix-command flakes' build --impure ".#$FLAKE_SYSTEM" "$@"

printf "%b%s%b\n" "$YELLOW" "Cleaning up..." "$NC"
unlink ./result

printf "%b%s%b\n" "$GREEN" "Switch to new generation complete!" "$NC"
