name: 'Setup Nix with Cache'
description: 'Install Nix and setup caching with week-based rotation'
inputs:
  enable-kvm:
    description: 'Enable KVM support (automatically enabled on Linux)'
    required: false
    default: 'true'
  cache-mode:
    description: 'Cache mode: "full" (save and restore) or "restore-only" (restore only)'
    required: false
    default: 'full'
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@da36cb69b1c3247ad7a1f931ebfd954a1105ef14 # v14
      with:
        extra-conf: |
          experimental-features = nix-command flakes
          accept-flake-config = true

    - name: Get week number for cache rotation
      id: date
      shell: bash
      run: echo "week=$(date +%Y-W%U)" >> $GITHUB_OUTPUT

    - name: Restore Nix cache (full mode)
      if: inputs.cache-mode == 'full'
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.cache/nix
          ~/.local/state/nix
        key: nix-${{ runner.os }}-${{ hashFiles(format('{0}/**/flake.lock', github.workspace)) }}-${{ steps.date.outputs.week }}
        restore-keys: |
          nix-${{ runner.os }}-${{ hashFiles(format('{0}/**/flake.lock', github.workspace)) }}-
          nix-${{ runner.os }}-
      continue-on-error: true

    - name: Restore Nix cache (restore-only mode)
      if: inputs.cache-mode == 'restore-only'
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.cache/nix
          ~/.local/state/nix
        key: nix-${{ runner.os }}-${{ hashFiles(format('{0}/**/flake.lock', github.workspace)) }}-${{ steps.date.outputs.week }}
        restore-keys: |
          nix-${{ runner.os }}-${{ hashFiles(format('{0}/**/flake.lock', github.workspace)) }}-
          nix-${{ runner.os }}-
      continue-on-error: true

    - name: Cache status check
      shell: bash
      run: |
        echo "🔍 Cache configuration:"
        echo "  - Cache mode: ${{ inputs.cache-mode }}"
        echo "  - Cache key: nix-${{ runner.os }}-${{ hashFiles(format('{0}/**/flake.lock', github.workspace)) }}-${{ steps.date.outputs.week }}"
        echo "  - Week: ${{ steps.date.outputs.week }}"
        echo "  - Flake.lock hash: ${{ hashFiles(format('{0}/**/flake.lock', github.workspace)) }}"

    - name: Save Nix cache (full mode only)
      if: inputs.cache-mode == 'full' && always()
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      continue-on-error: true
      with:
        path: |
          ~/.cache/nix
          ~/.local/state/nix
        key: nix-${{ runner.os }}-${{ hashFiles(format('{0}/**/flake.lock', github.workspace)) }}-${{ steps.date.outputs.week }}
