name: 'Setup Nix with Cache'
description: 'Install Nix and setup caching with week-based rotation'
inputs:
  enable-kvm:
    description: 'Enable KVM support (automatically enabled on Linux)'
    required: false
    default: 'true'
  cache-mode:
    description: 'Cache mode: "full" (save and restore) or "restore-only" (restore only)'
    required: false
    default: 'full'
runs:
  using: 'composite'
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21
      with:
        determinate: false
        extra-conf: |
          experimental-features = nix-command flakes
          accept-flake-config = true
          trusted-users = root *
          substituters = https://cache.nixos.org https://nix-community.cachix.org https://baleen-nix.cachix.org
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= baleen-nix.cachix.org-1:awgC7Sut148An/CZ6TZA+wnUtJmJnOvl5NThGio9j5k=

    - name: Install cachix for pushing
      shell: bash
      run: |
        nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
        echo "${{ secrets.CACHIX_AUTH_TOKEN }}" | cachix authtoken --stdin

    - name: Get week number for cache rotation
      id: date
      shell: bash
      run: echo "week=$(date +%Y-W%U)" >> $GITHUB_OUTPUT

    - name: Restore Nix cache (full mode)
      if: inputs.cache-mode == 'full'
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.cache/nix
          ~/.local/state/nix
        key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}-${{ steps.date.outputs.week }}-v3
        restore-keys: |
          nix-${{ runner.os }}-
      continue-on-error: true

    - name: Restore Nix cache (restore-only mode)
      if: inputs.cache-mode == 'restore-only'
      uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.cache/nix
          ~/.local/state/nix
        key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}-${{ steps.date.outputs.week }}-v3
        restore-keys: |
          nix-${{ runner.os }}-
      continue-on-error: true

    - name: Cache status check
      shell: bash
      run: |
        echo "🔍 Cache configuration:"
        echo "  - Cache mode: ${{ inputs.cache-mode }}"
        echo "  - Cache key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}-${{ steps.date.outputs.week }}"
        echo "  - Week: ${{ steps.date.outputs.week }}"
        echo "  - Flake.lock hash: ${{ hashFiles('**/flake.lock') }}"

    - name: Save Nix cache (full mode only)
      if: inputs.cache-mode == 'full' && always()
      uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      continue-on-error: true
      with:
        path: |
          ~/.cache/nix
          ~/.local/state/nix
        key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}-${{ steps.date.outputs.week }}-v3
