# GitHub Actions pre-commit workflow template
# Copy to .github/workflows/pre-commit.yml

name: pre-commit

on:
  pull_request:
  push:
    branches: [main, master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # For Node.js projects, uncomment:
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'

      - uses: pre-commit/action@v3.0.1
