name: Build Core
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-nix-only:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            max-jobs = auto
            cores = 0

      - name: Cache Nix store  
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: core-${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}
          restore-keys: |
            core-${{ runner.os }}-nix-
            ${{ runner.os }}-nix-

      - name: Build without Homebrew (fast test)
        timeout-minutes: 15
        run: |
          export USER=ci
          # Just evaluate the Darwin configuration structure
          nix eval --impure ".#darwinConfigurations.x86_64-darwin.system" --apply 'x: "ok"'
          # Build base packages only (skip homebrew)
          nix build --impure --no-link ".#darwinConfigurations.x86_64-darwin.system.config.environment.systemPackages" \
            --option max-jobs auto \
            --option cores 0