name: Build
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            system: x86_64-darwin
            kind: darwin
            build_attr: darwinConfigurations.x86_64-darwin.system
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            max-jobs = auto
            cores = 0

      - name: Cache Nix store  
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: ${{ runner.os }}-${{ matrix.system }}-build-${{ hashFiles('flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.system }}-build-
            ${{ runner.os }}-build-

      - name: Build flake outputs (with Homebrew)
        timeout-minutes: 45
        run: |
          export USER=ci
          echo "Building full Darwin system with Homebrew..."
          nix build --impure --no-link ".#${{ matrix.build_attr }}" \
            --option max-jobs auto \
            --option cores 0 \
            --option keep-going true
      - name: Run Nix flake checks
        run: make smoke SYSTEM=${{ matrix.system }}