name: Build
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            system: x86_64-darwin
            kind: darwin
            build_attr: darwinConfigurations.x86_64-darwin.system
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            max-jobs = auto
            cores = 0
            substituters = https://cache.nixos.org https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Cache Nix store
        uses: actions/cache@v4
        with:
          path: |
            /nix/store
            ~/.cache/nix
          key: ${{ runner.os }}-build-nix-${{ hashFiles('flake.lock', '**/*.nix') }}
          restore-keys: |
            ${{ runner.os }}-build-nix-
            ${{ runner.os }}-nix-

      - name: Build flake outputs
        timeout-minutes: 45
        run: |
          export USER=ci
          nix build --impure --no-link ".#${{ matrix.build_attr }}" --max-jobs auto --cores 0
      - name: Run Nix flake checks
        run: make smoke SYSTEM=${{ matrix.system }}