name: Build
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  core-build:
    strategy:
      matrix:
        include:
          - os: macos-13
            system: x86_64-darwin
          - os: macos-latest
            system: aarch64-darwin
          - os: ubuntu-latest
            system: x86_64-linux
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            max-jobs = auto
            cores = 0
            substituters = https://cache.nixos.org https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Cache Nix store
        uses: actions/cache@v4
        with:
          path: |
            /nix/store
            ~/.cache/nix
          key: ${{ runner.os }}-${{ matrix.system }}-core-nix-${{ hashFiles('flake.lock', 'modules/shared/**/*.nix', 'modules/darwin/packages.nix') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.system }}-core-nix-
            ${{ runner.os }}-${{ matrix.system }}-nix-
            ${{ runner.os }}-nix-

      - name: Build development shell
        timeout-minutes: 5
        run: |
          export USER=ci
          # Test basic development environment
          nix build --impure --no-link .#devShells.${{ matrix.system }}.default --max-jobs auto --cores 0

      - name: Build core Nix packages
        timeout-minutes: 10
        run: |
          export USER=ci
          # Build individual packages without system integration
          nix build --impure --no-link .#packages.${{ matrix.system }} --max-jobs auto --cores 0 || true
          # Validate flake structure
          nix flake check --impure --no-build --system ${{ matrix.system }}

      - name: Run core validation
        run: make smoke SYSTEM=${{ matrix.system }}

  full-build:
    runs-on: macos-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    needs: core-build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            max-jobs = auto
            cores = 0
            substituters = https://cache.nixos.org https://nix-community.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Cache Nix store
        uses: actions/cache@v4
        with:
          path: |
            /nix/store
            ~/.cache/nix
          key: ${{ runner.os }}-full-nix-${{ hashFiles('flake.lock', '**/*.nix') }}
          restore-keys: |
            ${{ runner.os }}-core-nix-
            ${{ runner.os }}-full-nix-
            ${{ runner.os }}-nix-

      - name: Build full system (with Homebrew)
        timeout-minutes: 30
        run: |
          export USER=ci
          nix build --impure --no-link .#darwinConfigurations.x86_64-darwin.system --max-jobs auto --cores 0

      - name: Run full validation
        run: make smoke SYSTEM=x86_64-darwin
