name: Build Matrix
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-matrix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            system: x86_64-darwin
            build_attr: darwinConfigurations.x86_64-darwin.system
          - os: macos-latest
            system: aarch64-darwin
            build_attr: darwinConfigurations.aarch64-darwin.system
          - os: ubuntu-latest
            system: x86_64-linux
            build_attr: nixosConfigurations.x86_64-linux.config.system.build.toplevel
          - os: ubuntu-latest
            system: aarch64-linux
            build_attr: nixosConfigurations.aarch64-linux.config.system.build.toplevel
    
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            max-jobs = auto
            cores = 0
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org/
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

      - name: Cache Nix store
        uses: actions/cache@v4
        with:
          path: |
            /nix/store
            ~/.cache/nix
          key: ${{ runner.os }}-${{ matrix.system }}-build-${{ hashFiles('flake.lock', 'flake.nix', 'modules/**/*.nix', 'hosts/**/*.nix') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.system }}-build-
            ${{ runner.os }}-${{ matrix.system }}-
            ${{ runner.os }}-build-

      - name: Build configuration
        timeout-minutes: 25
        run: |
          export USER=ci
          # Fast evaluation check first
          nix eval --impure ".#${{ matrix.build_attr }}" --apply 'x: "ok"'
          # Build with optimizations
          nix build --impure --no-link ".#${{ matrix.build_attr }}" \
            --option max-jobs auto \
            --option cores 0 \
            --option keep-going true \
            --option log-lines 50