name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run lint
        run: make lint

  # Required status check for auto-merge protection  
  lint-status:
    runs-on: ubuntu-latest
    needs: [lint]
    if: always()
    steps:
      - name: Check lint status
        run: |
          if [ "${{ needs.lint.result }}" != "success" ]; then
            echo "Lint failed"
            exit 1
          fi
          echo "Lint passed"