name: Lint
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Nix 설치
        uses: DeterminateSystems/nix-installer-action@v14
        with:
          logger: pretty

      - name: Magic Nix Cache 설정
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run lint in devShell
        run: nix develop --impure --command make lint
        env:
          USER: ${{ github.actor }}
