name: macOS Build-Switch Test

on:
  push:
    branches: [main, feature/tests-modernization]
    paths:
      - 'flake.nix'
      - 'modules/darwin/**'
      - 'hosts/darwin/**'
      - '.github/workflows/macos-build-switch.yml'
  pull_request:
    paths:
      - 'flake.nix'
      - 'modules/darwin/**'
      - 'hosts/darwin/**'
      - '.github/workflows/macos-build-switch.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

env:
  NIX_CONFIG: |
    max-jobs = auto
    cores = 0
    substituters = https://cache.nixos.org https://nix-community.cachix.org
    trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=

jobs:
  build-switch-test:
    name: macOS Build-Switch (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            os: macos-13
            system: x86_64-darwin
          - arch: aarch64
            os: macos-14
            system: aarch64-darwin
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean existing Nix installation
        continue-on-error: true
        run: |
          echo "🧹 Cleaning existing Nix installation..."
          set +e

          # Stop services
          sudo launchctl stop org.nixos.nix-daemon 2>/dev/null || true
          sudo launchctl unload /Library/LaunchDaemons/org.nixos.nix-daemon.plist 2>/dev/null || true

          # Unmount and remove
          sudo umount /nix 2>/dev/null || true
          sudo rm -rf /nix 2>/dev/null || true
          sudo rm -f /etc/synthetic.conf /Library/LaunchDaemons/org.nixos.* 2>/dev/null || true
          sudo rm -rf /etc/nix 2>/dev/null || true

          # Prepare for fresh install
          echo "nix" | sudo tee /etc/synthetic.conf > /dev/null 2>&1 || true
          sync
          sleep 2

          echo "✅ Cleanup completed"
          set -e

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          install_url: https://releases.nixos.org/nix/nix-2.18.8/install
          enable_kvm: true

      - name: Cache Nix store
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: |
            /nix/store
            ~/.cache/nix
            ~/.local/state/nix
          key: macos-build-switch-${{ matrix.system }}-${{ hashFiles('flake.lock', 'flake.nix', 'modules/darwin/**/*.nix', 'hosts/darwin/**/*.nix') }}
          restore-keys: |
            macos-build-switch-${{ matrix.system }}-${{ hashFiles('flake.lock', 'flake.nix') }}-
            macos-build-switch-${{ matrix.system }}-
            phase3-build-${{ runner.os }}-${{ matrix.system }}-
          save-always: true

      - name: Wait for Nix daemon
        run: |
          echo "⏳ Waiting for Nix daemon to be ready..."
          max_attempts=30
          attempt=0
          while ! nix --version >/dev/null 2>&1; do
            attempt=$((attempt + 1))
            if [[ $attempt -ge $max_attempts ]]; then
              echo "❌ Nix daemon failed to start"
              exit 1
            fi
            echo "Attempt $attempt/$max_attempts"
            sleep 5
          done
          echo "✅ Nix daemon is ready"
          nix --version

      - name: Test build-switch (dry-run)
        timeout-minutes: 45
        run: |
          export USER=${USER:-ci}
          echo "🔨 Testing build-switch for ${{ matrix.system }}"
          echo "Current USER: $USER"

          # Step 1: Build the configuration
          echo "📦 Step 1/3: Building Darwin configuration..."
          nix build --impure .#darwinConfigurations.${{ matrix.system }}.system \
            --verbose \
            --show-trace \
            --keep-going

          if [ ! -L "./result" ]; then
            echo "❌ Build result not found!"
            exit 1
          fi

          echo "✅ Build completed successfully"
          ls -lh result/

          # Step 2: Check activationPackage exists
          echo "🔍 Step 2/3: Verifying activation package..."
          if [ -d "result/sw" ]; then
            echo "✅ Activation package found at result/sw"
            ls -lh result/sw/bin/ | head -20
          else
            echo "❌ Activation package not found!"
            exit 1
          fi

          # Step 3: Dry-run activation (without actual system modification)
          echo "🧪 Step 3/3: Testing activation script (dry-run)..."

          # Check if darwin-rebuild exists in the build
          if [ -f "result/sw/bin/darwin-rebuild" ]; then
            echo "✅ darwin-rebuild found in build output"

            # Test the command help to verify it's functional
            result/sw/bin/darwin-rebuild --help || {
              echo "⚠️ darwin-rebuild help failed, but binary exists"
            }
          else
            echo "❌ darwin-rebuild not found in result/sw/bin/"
            echo "Available binaries:"
            ls result/sw/bin/ | grep darwin || echo "No darwin-related binaries found"
            exit 1
          fi

          # Verify the activation script structure
          if [ -f "result/activate" ] || [ -f "result/sw/activate" ]; then
            echo "✅ Activation script found"
          else
            echo "⚠️ No activation script found, but this may be normal for nix-darwin"
          fi

          echo "✅ Build-switch validation completed successfully"
          echo "📊 Build output size: $(du -sh result | cut -f1)"

      - name: Test Makefile build-switch target
        timeout-minutes: 45
        run: |
          export USER=${USER:-ci}
          echo "🔨 Testing Makefile build-switch target..."

          # Clean previous result
          rm -f result

          # Run the actual Makefile target (which builds and attempts switch)
          # We'll catch the error when it tries to actually switch
          set +e
          make build-switch HOST=${{ matrix.system }} 2>&1 | tee build-switch.log
          exit_code=$?
          set -e

          # Check if build succeeded even if switch failed
          if grep -q "Build and switch completed" build-switch.log; then
            echo "✅ Build-switch completed (actual switch succeeded)"
            exit 0
          elif grep -q "Building Darwin configuration" build-switch.log && [ -L "./result" ]; then
            echo "✅ Build succeeded (switch may have failed, which is expected in CI)"
            echo "Exit code was: $exit_code"

            # Show the error for debugging but don't fail
            echo "Switch output:"
            tail -50 build-switch.log

            # If build was successful, consider this a pass
            if [ -L "./result" ]; then
              echo "✅ Build artifact exists, marking as success"
              exit 0
            fi
          else
            echo "❌ Build-switch failed unexpectedly"
            tail -100 build-switch.log
            exit 1
          fi

      - name: Summary
        if: always()
        run: |
          echo "================================"
          echo "macOS Build-Switch Test Summary"
          echo "================================"
          echo "Architecture: ${{ matrix.arch }}"
          echo "System: ${{ matrix.system }}"
          echo "OS: ${{ matrix.os }}"
          echo ""

          if [ -L "./result" ]; then
            echo "✅ Build artifact: EXISTS"
            echo "Build size: $(du -sh result | cut -f1)"
          else
            echo "❌ Build artifact: MISSING"
          fi

          echo ""
          echo "This workflow validates that:"
          echo "  1. ✅ Darwin configuration builds successfully"
          echo "  2. ✅ All activation scripts are present"
          echo "  3. ✅ The Makefile build-switch target works"
          echo "  4. ℹ️  Actual system switch is not performed in CI"

      - name: Upload build logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-switch-logs-${{ matrix.arch }}-${{ github.run_number }}
          path: |
            build-switch.log
            *.log
          retention-days: 7

  summary:
    name: Build-Switch Summary
    needs: build-switch-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check results
        run: |
          result="${{ needs.build-switch-test.result }}"

          if [[ "$result" == "success" ]]; then
            echo "✅ All macOS build-switch tests passed"
            exit 0
          else
            echo "❌ Some macOS build-switch tests failed"
            echo "Result: $result"
            exit 1
          fi
