# .github/workflows/test.yml
name: CI

permissions:
  contents: read         # repo 내용 접근

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-build-test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            kind: darwin
            flake_attr: darwinConfigurations
          - os: ubuntu-latest
            kind: linux
            flake_attr: homeConfigurations
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run all Nix/flake/home-manager tests (verify-all)
        run: |
          make verify-all
