# .github/workflows/ci.yml
name: CI

permissions:
  contents: read         # repo 내용 접근
  actions: write         # actions/<…> 메타데이터 접근 권한

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable


      - name: Pre-fetch flake inputs
        run: nix flake update --recreate-lock-file

      - name: Build all outputs
        run: nix build --impure --no-link

      - name: Run tests
        run: nix flake check

      - uses: actions/upload-artifact@v3
        with:
          name: build-results-${{ matrix.os }}
          path: ./result
