name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read         # repo 내용 접근

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run lint
        run: make lint

  smoke:
    needs: lint
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: ubuntu-latest
            system: aarch64-linux
          - os: macos-latest
            system: x86_64-darwin
          - os: macos-latest
            system: aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Cache Nix store
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-
      - name: Run smoke test
        run: |
          make smoke SYSTEM=${{ matrix.system }}

  build-test:
    needs: [lint, smoke]
    strategy:
      matrix:
        include:
          - os: macos-latest
            system: x86_64-darwin
            kind: darwin
            build_attr: darwinConfigurations.x86_64-darwin.system
          - os: macos-latest
            system: aarch64-darwin
            kind: darwin
            build_attr: darwinConfigurations.aarch64-darwin.system
          - os: ubuntu-latest
            system: x86_64-linux
            kind: linux
            build_attr: nixosConfigurations.x86_64-linux.config.system.build.toplevel
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Cache Nix store
        uses: actions/cache@v4
        with:
          path: /nix/store
          key: ${{ runner.os }}-nix-${{ hashFiles('flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-nix-

      - name: Build flake outputs
        run: |
          nix build --no-link ".#${{ matrix.build_attr }}"
      - name: Run Nix flake checks
        run: |
          make smoke SYSTEM=${{ matrix.system }}
