name: Fast Tests
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-fast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            max-jobs = auto
            cores = 0

      - name: Cache test results
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/nix
            /nix/store
          key: ${{ runner.os }}-tests-${{ hashFiles('tests/**/*.nix', 'flake.lock') }}
          restore-keys: |
            ${{ runner.os }}-tests-

      - name: Run unit tests (parallel)
        run: |
          export USER=ci
          # Run individual tests in parallel
          cd tests
          find . -name "*.nix" -type f | \
            xargs -P 4 -I {} bash -c 'echo "Testing {}" && nix eval --impure ..#checks.$(nix eval --impure --expr "builtins.currentSystem").$(basename {} .nix)'