name: Test
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            max-jobs = auto
            cores = 0
      - name: Cache Nix store  
        uses: actions/cache@v4
        with:
          path: |
            /nix/store
            ~/.cache/nix
          key: ${{ runner.os }}-test-nix-${{ hashFiles('flake.lock', 'tests/**/*.nix') }}
          restore-keys: |
            ${{ runner.os }}-test-nix-
            ${{ runner.os }}-nix-
      - name: Run tests
        run: |
          export USER=ci
          # Run tests with parallelization
          make test ARGS="--max-jobs auto --cores 0"