# .github/workflows/test.yml
name: CI

permissions:
  contents: read         # repo 내용 접근

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  build-test:
    needs: lint
    strategy:
      matrix:
        include:
          - os: macos-latest
            kind: darwin
            system: x86_64-darwin
            flake_attr: darwinConfigurations
          - os: macos-latest
            kind: darwin
            system: aarch64-darwin
            flake_attr: darwinConfigurations
          - os: ubuntu-latest
            kind: linux
            system: x86_64-linux
            flake_attr: homeConfigurations
          - os: ubuntu-latest
            kind: linux
            system: aarch64-linux
            flake_attr: homeConfigurations
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build flake outputs
        run: |
          nix build --no-link
      - name: Run Nix flake checks
        run: |
          nix flake check --system ${{ matrix.system }} --no-build
