name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read         # repo 내용 접근

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  smoke:
    needs: lint
    strategy:
      matrix:
        include:
          - &linux_x86
            os: ubuntu-latest
            system: x86_64-linux
          - &linux_arm
            os: ubuntu-latest
            system: aarch64-linux
          - &darwin_x86
            os: macos-latest
            system: x86_64-darwin
          - &darwin_arm
            os: macos-latest
            system: aarch64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run smoke test
        run: |
          nix flake check --system ${{ matrix.system }} --no-build

  build-test:
    needs: [lint, smoke]
    strategy:
      matrix:
        include:
          - <<: *darwin_x86
            kind: darwin
            build_attr: darwinConfigurations.x86_64-darwin.system
          - <<: *darwin_arm
            kind: darwin
            build_attr: darwinConfigurations.aarch64-darwin.system
          - <<: *linux_x86
            kind: linux
            build_attr: nixosConfigurations.x86_64-linux.config.system.build.toplevel
          - <<: *linux_arm
            kind: linux
            build_attr: nixosConfigurations.aarch64-linux.config.system.build.toplevel
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build flake outputs
        run: |
          nix build --no-link ".#${{ matrix.build_attr }}"
      - name: Run Nix flake checks
        run: |
          nix flake check --system ${{ matrix.system }} --no-build
