# .github/workflows/test.yml
name: CI

permissions:
  contents: read         # repo 내용 접근

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  smoke:
    needs: lint
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: x86_64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run smoke test
        run: |
          nix flake check --system ${{ matrix.system }} --no-build

  smoke-devshell:
    needs: lint
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: macos-latest
            system: x86_64-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run devShell smoke test
        run: |
          nix develop . --system ${{ matrix.system }} -c true

  build-test:
    needs: [lint, smoke, smoke-devshell]
    strategy:
      matrix:
        include:
          - os: macos-latest
            system: x86_64-darwin
            kind: darwin
            build_attr: darwinConfigurations.x86_64-darwin.system
          - os: ubuntu-latest
            system: x86_64-linux
            kind: linux
            build_attr: nixosConfigurations.x86_64-linux.config.system.build.toplevel
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build flake outputs
        run: |
          nix build --no-link ".#${{ matrix.build_attr }}"
      - name: Run Nix flake checks
        run: |
          nix flake check --system ${{ matrix.system }} --no-build
