# .github/workflows/test.yml
name: CI

permissions:
  contents: read         # repo 내용 접근

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Nix smoke test
        run: |
          nix --version
          nix flake show

      - name: Build all outputs
        run: |
          nix build --impure --no-link

      - name: Run nvim (smoke test)
        run: |
          ./result/bin/nvim --version

      - name: Run tests
        run: nix flake check
