name: Test setup Mac machine

on: [push]

jobs:
  macos_build:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: test
        id: test
        run: |
          set -eo pipefail
          bash ./utils/brew.sh
#      - name: Run setup_new_mach_machine script
#        run: |
#          set -eo pipefail
#          export CI=1
#          bash install.sh
