# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read           # (기본) repo 내 코드 읽기
  actions: write           # actions/<…> 메타데이터 읽기·쓰기

jobs:
  lint-build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      # Nix 3.0+ 설치 (macOS에서도 동작)
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      # Optional: Flake 의존성 미리 가져오기 (캐시 가속)
      - name: Pre-fetch flake inputs
        run: nix flake update --recreate-lock-file

      # 1) 빌드
      - name: Build all outputs
        run: nix build --impure --no-link

      # 2) 테스트
      - name: Run tests
        run: nix flake check

      # 3) (Optional) Artifacts 업로드
      - uses: actions/upload-artifact@v3
        with:
          name: build-results-${{ matrix.os }}
          path: ./result
