# .github/workflows/test.yml
name: CI

permissions:
  contents: read         # repo 내용 접근

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-build-test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            kind: darwin
            flake_attr: darwinConfigurations
          - os: ubuntu-latest
            kind: linux
            flake_attr: homeConfigurations
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run build-test (빌드/스모크/드라이런)
        run: |
          make build-test
      - name: Run e2e-test (NixOS VM 기반 end-to-end)
        run: |
          make e2e-test
      - name: Run Nix flake checks (NixOS VM test 포함)
        run: |
          nix flake check --system ${{ matrix.system }} --no-build
